homework_3_task_1_Romanyuk
wrdxwrdxwrdx/spbu_python_sem1 pull request #13
Opened 2023-10-02 17:01 UTC by wrdxwrdxwrdx

2023-10-12 18:19 UTC, toadharvard requested changes

2023-10-12 18:19 UTC, toadharvard commented on src/homeworks/homework_3/homework_3_task_1_Romanyuk.py
> +        return False
Бред какой-то, у тебя функция что возвращает? Другую функцию
False неуместен и должен быть заменен на что-то другое (exception выбрось лучше)

2023-10-12 18:19 UTC, toadharvard commented on src/homeworks/homework_3/homework_3_task_1_Romanyuk.py
> +            return function()
Вернул результат, а не функцию. Снова сигнатура нарушена

2023-10-12 18:19 UTC, toadharvard commented on src/homeworks/homework_3/homework_3_task_1_Romanyuk.py
> +            eval(input("Введите название функции и ее параметры: "))
???

2023-10-12 18:28 UTC, toadharvard commented
Название коммитов кринж

2023-10-16 20:48 UTC, toadharvard commented
Для первой практики с исключениями норм, но дальше нужно тренироваться. LGTM

2023-10-16 20:48 UTC, toadharvard approved these changes

2023-10-17 09:49 UTC, SpirinEgor commented on src/homeworks/homework_3/homework_3_task_1_Romanyuk.py
> +                raise ValueError("введена неверная арность(curry_explict)")
Мне не нравится такое использование исключений :( Если хочется контролировать правильность вызова, то надо
1. Использовать, например, [`inspect.signature`](https://docs.python.org/3/library/inspect.html#inspect.signature) и честно извлекать число параметров у функции
2. Проверять это в начале `curry_explicit` и дальше работать в безопасной зоне (все вызовы корректны)

2023-10-17 09:49 UTC, SpirinEgor commented on src/homeworks/homework_3/homework_3_task_1_Romanyuk.py
> +def curry_explict(function, arity):
`explicit`

2023-10-17 09:50 UTC, SpirinEgor commented on src/homeworks/homework_3/homework_3_task_1_Romanyuk.py
> +        return lambda new_argument: main_curry_function([*args, new_argument])
Возможно, выделить в отдельную функцию и внутри нее делать `args.append(new_argument)` будет чуть эффективнее

2023-10-17 09:50 UTC, SpirinEgor commented on src/homeworks/homework_3/homework_3_task_1_Romanyuk.py
> +        try:
Такое точно нельзя, что тут пытаешься отловить? В каждой строчке что-то может пойти не так?

2023-10-17 20:00 UTC, toadharvard commented on src/homeworks/homework_3/homework_3_task_1_Romanyuk.py
> +            raise ValueError("введена неверная арность(uncurry_explicit)")
Бро, тут тоже забыл подчистить)

2023-10-26 12:38 UTC, SpirinEgor approved these changes

2023-10-26 12:38 UTC, merged