homework_4_task_1_Romanyuk
wrdxwrdxwrdx/spbu_python_sem1 pull request #18
Opened 2023-10-17 19:34 UTC by wrdxwrdxwrdx

2023-10-28 11:31 UTC, toadharvard requested changes

2023-10-28 11:31 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_1_Romanyuk.py
> +        answer = list(map(lambda a: 0 if a else 1, answer))
<3

2023-10-28 11:31 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_1_Romanyuk.py
> +        b = [b[0] for i in range(len(a) - len(b) + 2)] + b[1:]
эти границы плохо читаются, поэтому я не могу гарантировать, что ошибки нет, подумаешь как переписать более понятно?

2023-10-28 11:31 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_1_Romanyuk.py
> +    if number[0] == 0:
две строки в if/else не отличаются, чзх?

2023-10-28 11:31 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_1_Romanyuk.py
> +    for i in range(len(b) - 1, -1, -1):
лучше было бы сразу в первом цикле добавлять перенос разряда

2023-11-02 22:30 UTC, toadharvard requested changes

2023-11-02 22:30 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_1_Romanyuk.py
> +    return (-1) ** is_minus * answer
Возводить в степень условия это интересное решение конечно.
Норм выпендриваешься, только читаемее в разы было бы, если бы ты не жалел переменные и более явно выражал, что именно в is_minus. Только ты и я знаем, что там {0, 1}, а по названию неясно.

2023-11-02 22:30 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_1_Romanyuk.py
> +    return list(map(lambda x: int(not x), number))
Это не буллы чувак, напиши нормальное условие, а не `int(not x)`

2023-11-02 22:30 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_1_Romanyuk.py
> +        answer.insert(0, number % 2)
Лучше было бы хранить числа в обратном порядке, потому что добавление в начало - O(n), а в конец - O(1). Тут у тебя на каждую итерацию O(n) времени.

2023-11-02 22:30 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_1_Romanyuk.py
> +    is_minus = number < 0
опять

2023-11-02 22:30 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_1_Romanyuk.py
> +        answer.insert(0, sum_digit % 2)
O(n)

2023-11-02 22:30 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_1_Romanyuk.py
> +    is_minus = number.pop(0)
O(n)

2023-11-02 22:30 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_1_Romanyuk.py
> +    num_2 = binary_addition(inverse_number(num_2), normalize_binary([0, 1], len(num_2)))
Переименовал переменную зачем?

2023-11-02 22:30 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_1_Romanyuk.py
> +        normalize_binary(num_1, bytes * 8), normalize_binary(num_2, bytes * 8)
Зачем на 8 умножаешь?

2023-11-12 12:41 UTC, toadharvard approved these changes
Ну так. Сойдет, но на вопросы отвечать надо, я зачем их тебе задаю при проверке?

2023-11-28 11:28 UTC, SpirinEgor approved these changes

2023-11-28 11:28 UTC, merged