homework_4_task_2_Romanyuk
wrdxwrdxwrdx/spbu_python_sem1 pull request #19
Opened 2023-10-17 19:36 UTC by wrdxwrdxwrdx

2023-10-29 15:28 UTC, toadharvard requested changes

2023-10-29 15:28 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_2_Romanyuk.py
> +def denary_exponent(number):
Не соответствует примерам из задания

2023-10-29 15:28 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_2_Romanyuk.py
> +    exponent = denary_to_binary(count_shifted_order(q, exponent_bit))[1:-1]
Хз, что ты тут делаешь, напиши нормальные функции с адекватными названиями, а не однострочник

2023-10-29 15:28 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_2_Romanyuk.py
> +    bin_number = denary_to_binary(number, mantissa_bit + 2)
Почему +2?

2023-10-29 15:28 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_2_Romanyuk.py
> +        bin_number[2 : bin_number.index(".")] + bin_number[bin_number.index(".") + 1 :]
Хз, что ты тут делаешь, напиши нормальные функции с адекватными названиями, а не однострочник

2023-10-29 15:28 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_2_Romanyuk.py
> +def denary_to_binary(number, accuracy=10):
Вынеси часть кода в отдельные функции

2023-11-12 10:22 UTC, toadharvard approved these changes

2023-11-12 10:22 UTC, toadharvard commented on src/homeworks/homework_4/homework_4_task_2_Romanyuk.py
> +    output.append(".")
Вообще это напрашивается в 35 строчку, но ок

2023-11-28 11:29 UTC, SpirinEgor approved these changes

2023-11-28 11:29 UTC, merged