homework_4_task_3_Romanyuk
wrdxwrdxwrdx/spbu_python_sem1 pull request #20
Opened 2023-10-17 19:37 UTC by wrdxwrdxwrdx

2023-10-29 15:38 UTC, toadharvard requested changes

2023-10-29 15:38 UTC, toadharvard commented on src/homeworks/homework_4/task_4/queue.py
> +    next: any
Найс типы

Тут конкретно 
next: 'Node'

Или from __future__ import annotations
next: Node

2023-10-29 15:41 UTC, toadharvard requested changes

2023-10-29 15:41 UTC, toadharvard commented on src/homeworks/homework_4/task_4/queue.py
> +    head: Node = None
Формально тип: head: Node | None = None

2023-11-02 20:06 UTC, toadharvard requested changes
Типы. Где? Обсуждали.

2023-11-11 17:51 UTC, toadharvard approved these changes

2023-11-28 11:30 UTC, SpirinEgor approved these changes

2023-11-28 11:30 UTC, merged